- name: Geerlingguy Docker
  gather_facts: No
  any_errors_fatal: true
  hosts: _development
  become: true
  roles:
    - geerlingguy.docker

- name: Postgre
  hosts: _ansible_postgresql
  become: true
  roles:
    - postgre

- name: Nodejs
  hosts: _ansible_nodejs
  become: true
  roles:
    - nodejs

- name: React
  hosts: _ansible_react
  become: true
  roles:
    - react
